#===============================================================================
# DRAGON-type Moves
#===============================================================================

Data::Move.register(:ETERNABEAM) do
  name "Eternabeam"
  function_code "AttackAndSkipNextTurn"
  base_damage 160
  type :DRAGON
  category :Special
  accuracy 90
  total_pp 5
  target :NearOther
  flags :CanProtect, :CanMirrorMove, :CannotMetronome
  description "This is Eternatus's most powerful attack in its original form. The user can't move on the next turn."
end

Data::Move.register(:DRAGONENERGY) do
  name "Dragon Energy"
  function_code "PowerHigherWithUserHP"
  base_damage 150
  type :DRAGON
  category :Special
  accuracy 100
  total_pp 5
  target :AllNearFoes
  flags :CanProtect, :CanMirrorMove, :CannotMetronome
  description "Converts life-force into power to attack. The lower the user's HP, the lower the move's power."
end

Data::Move.register(:ROAROFTIME) do
  name "Roar of Time"
  function_code "AttackAndSkipNextTurn"
  base_damage 150
  type :DRAGON
  category :Special
  accuracy 90
  total_pp 5
  target :NearOther
  flags :CanProtect, :CanMirrorMove
  description "The user blasts the target with power that distorts even time. The user must rest on the next turn."
end

Data::Move.register(:DRACOMETEOR) do
  name "Draco Meteor"
  function_code "LowerUserSpAtk2"
  base_damage 130
  type :DRAGON
  category :Special
  accuracy 90
  total_pp 5
  target :NearOther
  flags :CanProtect, :CanMirrorMove
  description "Comets are summoned down from the sky. The attack's recoil harshly reduces the user's Sp. Atk stat."
end

Data::Move.register(:OUTRAGE) do
  name "Outrage"
  function_code "MultiTurnAttackConfuseUserAtEnd"
  base_damage 120
  type :DRAGON
  category :Physical
  accuracy 100
  total_pp 10
  target :RandomNearFoe
  flags :Contact, :CanProtect, :CanMirrorMove
  description "The user rampages and attacks for two to three turns. It then becomes confused, however."
end

Data::Move.register(:CLANGINGSCALES) do
  name "Clanging Scales"
  function_code "LowerUserDefense1"
  base_damage 110
  type :DRAGON
  category :Special
  accuracy 100
  total_pp 5
  target :AllNearFoes
  flags :CanProtect, :CanMirrorMove, :Sound
  description "The user rubs its scales and makes a huge noise. Also lowers the user's Defense stat."
end

Data::Move.register(:COREENFORCER) do
  name "Core Enforcer"
  function_code "NegateTargetAbilityIfTargetActed"
  base_damage 100
  type :DRAGON
  category :Special
  accuracy 100
  total_pp 10
  target :AllNearFoes
  flags :CanProtect, :CanMirrorMove
  description "If the target has already moved this turn, the effect of its Ability is negated."
end

Data::Move.register(:DRAGONRUSH) do
  name "Dragon Rush"
  function_code "FlinchTarget"
  base_damage 100
  type :DRAGON
  category :Physical
  accuracy 75
  total_pp 10
  target :NearOther
  flags :Contact, :CanProtect, :CanMirrorMove, :TramplesMinimize
  description "The user tackles the foe while exhibiting overwhelming menace. It may also make the target flinch."
end

Data::Move.register(:SPACIALREND) do
  name "Spacial Rend"
  function_code "None"
  base_damage 100
  type :DRAGON
  category :Special
  accuracy 95
  total_pp 5
  target :NearOther
  flags :CanProtect, :CanMirrorMove, :HighCriticalHitRate
  description "The user tears the target along with the space around it. Critical hits land more easily."
end

Data::Move.register(:DRAGONHAMMER) do
  name "Dragon Hammer"
  function_code "None"
  base_damage 90
  type :DRAGON
  category :Physical
  accuracy 100
  total_pp 15
  target :NearOther
  flags :Contact, :CanProtect, :CanMirrorMove
  description "The user uses its body like a hammer to attack the target and inflict damage."
end

Data::Move.register(:DRAGONPULSE) do
  name "Dragon Pulse"
  function_code "None"
  base_damage 85
  type :DRAGON
  category :Special
  accuracy 100
  total_pp 10
  target :Other
  flags :CanProtect, :CanMirrorMove, :Pulse
  description "The target is attacked with a shock wave generated by the user's gaping mouth."
end

Data::Move.register(:DRAGONCLAW) do
  name "Dragon Claw"
  function_code "None"
  base_damage 80
  type :DRAGON
  category :Physical
  accuracy 100
  total_pp 15
  target :NearOther
  flags :Contact, :CanProtect, :CanMirrorMove
  description "The user slashes the target with huge, sharp claws."
end

Data::Move.register(:BREAKINGSWIPE) do
  name "Breaking Swipe"
  function_code "LowerTargetAttack1"
  base_damage 60
  type :DRAGON
  category :Physical
  accuracy 100
  total_pp 15
  target :AllNearFoes
  flags :Contact, :CanProtect, :CanMirrorMove, :CannotMetronome
  description "The user swings its tough tail wildly and attacks all foes. This also lowers their Attack stats."
end

Data::Move.register(:DRAGONBREATH) do
  name "Dragon Breath"
  function_code "ParalyzeTarget"
  base_damage 60
  type :DRAGON
  category :Special
  accuracy 100
  total_pp 20
  target :NearOther
  flags :CanProtect, :CanMirrorMove
  description "The user exhales a mighty gust that inflicts damage. It may also leave the target with paralysis."
end

Data::Move.register(:DRAGONTAIL) do
  name "Dragon Tail"
  function_code "SwitchOutTargetDamagingMove"
  base_damage 60
  type :DRAGON
  category :Physical
  accuracy 90
  total_pp 10
  target :NearOther
  priority -6
  flags :Contact, :CanProtect, :CanMirrorMove
  description "The user knocks away the target and drags out another Pokémon in its party. In the wild, the battle ends."
end

Data::Move.register(:DRAGONDARTS) do
  name "Dragon Darts"
  function_code "HitTwoTimesTargetThenTargetAlly"
  base_damage 50
  type :DRAGON
  category :Physical
  accuracy 100
  total_pp 10
  target :NearOther
  flags :CanProtect, :CanMirrorMove
  description "The user attacks twice using Dreepy. If there are two targets, this move hits each one once."
end

Data::Move.register(:DUALCHOP) do
  name "Dual Chop"
  function_code "HitTwoTimes"
  base_damage 40
  type :DRAGON
  category :Physical
  accuracy 90
  total_pp 15
  target :NearOther
  flags :Contact, :CanProtect, :CanMirrorMove
  description "The user attacks its target by hitting it with brutal strikes. The target is hit twice in a row."
end

Data::Move.register(:TWISTER) do
  name "Twister"
  function_code "FlinchTargetDoublePowerIfTargetInSky"
  base_damage 40
  type :DRAGON
  category :Special
  accuracy 100
  total_pp 20
  target :AllNearFoes
  flags :CanProtect, :CanMirrorMove
  description "The user whips up a vicious tornado to tear at the opposing team. It may also make targets flinch."
end

Data::Move.register(:SCALESHOT) do
  name "Scale Shot"
  function_code "HitTwoToFiveTimesRaiseUserSpd1LowerUserDef1"
  base_damage 25
  type :DRAGON
  category :Physical
  accuracy 90
  total_pp 20
  target :NearOther
  flags :CanProtect, :CanMirrorMove
  description "Attacks by shooting scales two to five times in a row. Boosts the user's Speed but lowers its Defense."
end

Data::Move.register(:DRAGONRAGE) do
  name "Dragon Rage"
  function_code "FixedDamage40"
  base_damage 1
  type :DRAGON
  category :Special
  accuracy 100
  total_pp 10
  target :NearOther
  flags :CanProtect, :CanMirrorMove
  description "This attack hits the target with a shock wave of pure rage. This attack always inflicts 40 HP damage."
end

